{% set name = "igwn-lldd-common" %}
{% set version = "0.4.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 29d50910ae189b82e279c211f34867174f61a54d8a170421e94ed6f84c8e0aa0

build:
  entry_points:
    - kafka2frame = igwn_lldd_common.kafka2frame:main
    - frame2kafka = igwn_lldd_common.frame2kafka:main
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=38.2.5
  run:
    - __unix  # [unix]
    - __win  # [win]
    - configargparse
    - gpstime
    - python >={{ python_min }}
    - python-confluent-kafka
    - watchdog
    - python-framel >=8.47.2  # [not win]

test:
  requires:
    - flaky
    - kafka-python-ng
    - pip
    - pytest
    - python {{ python_min }}
  commands:
    # check metadata
    - python -m pip check igwn-lldd-common
    - python -m pip show igwn-lldd-common
    # run test suite
    - python -m pytest -ra -v --pyargs igwn_lldd_common.tests
    # check entry points
    - frame2kafka --help
    - kafka2frame --help

about:
  home: https://git.ligo.org/computing/lowlatency/igwn-lldd-common
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: The IGWN - Low Latency Data Distribution (lldd) is software to distribute low latency data used by the International Gravitational-Wave Observatory Network (IGWN).

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
    - rhyspoulton
