{% set name = "igwn-lldd-common" %}
{% set version = "0.4.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1e2b4dcf1145bbd1c40b0a72b1f62dd75fcfafa46374819aeead172e1afc7ff3

build:
  entry_points:
    - kafka2frame = igwn_lldd_common.kafka2frame:main
    - frame2kafka = igwn_lldd_common.frame2kafka:main
  number: 1
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    - pip
    - python
    - setuptools >=38.2.5
  run:
    - configargparse
    - gpstime
    - python
    - python-confluent-kafka
    - ujson
    - watchdog
    - python-framel >=8.47.2  # [not win]

test:
  requires:
    - flaky
    - kafka-python
    - pip
    - pytest
  commands:
    # check metadata
    - python -m pip check igwn-lldd-common
    - python -m pip show igwn-lldd-common
    # run test suite
    - python -m pytest -ra -v --pyargs igwn_lldd_common.tests
    # check entry points
    - frame2kafka --help
    - kafka2frame --help

about:
  home: https://git.ligo.org/computing/lowlatency/igwn-lldd-common
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: The IGWN - Low Latency Data Distribution (lldd) is software to distribute low latency data used by the International Gravitational-Wave Observatory Network (IGWN).

extra:
  recipe-maintainers:
    - duncanmmacleod
    - myNameIsPatrick
    - rhyspoulton
